kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-amq-2
  labels:
    type: local
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/opt/amq2"